#**************************************************************************
# Copyright (c) 2012 Digi International Inc.,
# All rights not expressly granted are reserved.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Digi International Inc. 11001 Bren Road East, Minnetonka, MN 55343
#
#**************************************************************************

from __future__ import print_function

base_list = [
    'assertLogin',
    'authenticate',
    'changePassword',
    'createSecurityQuestion',
    'findSecurityQuestionByUserName',
    'resetPassword',
    'searchLoginHistory',
    'validateSecurityQuestion',
    'searchAsset',
    'getAsset',
]


asset_list = [
    'addAssetsToAssetGroup',
    'archiveAsset',
    'assetsShowOnMapAsKML',
    'createAsset',
    'createAssetConfiguration',
    'createAssetGroup',
    'createAssetType',
    'deleteAsset',
    'deleteAssetGroup',
    'deleteAssetType',
    'getAsset',
    'getAssetGroup',
    'getAssetType',
    'getAssetTypes',
    'pollAsset',
    'removeAllAssetsFromAssetGroup',
    'removeAssetsFromAssetGroup',
    'removeGeofence',
    'searchAsset',
    'searchAssetGroup',
    'searchAssetType',
    'updateAsset',
    'updateAssetGroup',
    'updateAssetType',
]


geofencing_list = [
    'applyGeofence',
    'checkPointOnGeofence',
    'createGeofence',
    'createGeofenceType',
    'deleteGeofence',
    'deleteGeofenceType',
    'getGeofenceByID',
    'getGeofenceTypeByID',
    'getGeofenceTypesList',
    'getGeofences',
    'updateGeofence',
    'removeGeofnence',
]

tracking_list = [
    'changeTrackSetting',
    'getAssetAlertsByAssetID',
    'getAssetTracksByAssetID',
    'getAssetTracksByAssetIDAsKML',
    'insertParseData',
    'setEngineIdlingFeature',
    'setGPRSTrackingFeature',
    'setNormalTrackingFeature',
    'setOBDFeature',
    'setOverSpeedFeature',
    'setPowerManagementFeature',
    'setRashDrivingFeature',
    'setSOSFeature',
    'startTracking',
    'stopTracking',
]


landmarks_routes_list = [
    'checkPointOnRoute',
    'createLandmark',
    'createLandmarkType',
    'createRoute',
    'createRouteType',
    'deleteLandmark',
    'deleteLandmarkType',
    'deleteRoute',
    'deleteRouteType',
    'findLandmarkTypeById',
    'geocodingService',
    'getDiagnosticData',
    'getKMLDataForReplay',
    'getLandmarkByID',
    'getLandmarkTypesList',
    'getLandmarks',
    'getRouteByID',
    'getRouteTypeByID',
    'getRouteTypesList',
    'getRoutes',
    'reverseGeocodingService',
    'searchLandmarksInsideGeofence',
    'searchLandmarksNearRoute',
    'updateLandmark',
    'updateRoute',
]


user_list = [
    'activateUser',
    'addUserToUserGroup',
    'checkPermission',
    'createUser',
    'createUserGroup',
    'deActivateUser',
    'findOrganizationById',
    'findOrganizationByName',
    'findPortalByName',
    'findPortalByUser',
    'findUserGroupByOrgId',
    'findUserProfileByUserName',
    'generatePassword',
    'getContactTypes',
    'getOrgTypes',
    'getPortal',
    'getServices',
    'getUserGroup',
    'removeUserFromUserGroup',
    'searchOrganization',
    'searchUser',
    'updateGeneratedPassword',
    'updateOrganization',
    'updatePortal',
    'updateUser',
    'activateOrganization',
    'addPermissionToRole',
    'addRolesToUserGroup',
    'createOrganization',
    'createPortal',
    'deActivateOrganization',
    'removePermissionFromRole',
    'removeRolesFromUserGroup',
]


device_list = [
    'searchAsset',
    'getAsset',
    'addDevicesToDeviceGroup',
    'archiveDevice',
    'assignGeofence',
    'createDevice',
    'createDeviceConfiguration',
    'createDeviceGroup',
    'createDeviceType',
    'createDeviceTypeConfiguration',
    'createHomeGPRSIP',
    'createHomeMobileNumber',
    'createMasterFeature',
    'deleteDeviceConfiguration',
    'deleteDeviceGroup',
    'deleteDeviceType',
    'deleteDeviceTypeConfiguration',
    'deleteHomeGPRSIP',
    'deleteHomeMobileNumber',
    'deleteMasterFeature',
    'findDeviceRecordIdsByDuration',
    'findDeviceRecordsByDuration',
    'getDevice',
    'getDeviceConfiguration',
    'getDeviceGroup',
    'getDeviceRecord',
    'getDeviceRecordIDs',
    'getDeviceType',
    'getDeviceTypeConfiguration',
    'getHomeGPRSIP',
    'getHomeMobileNumber',
    'getMasterFeature',
    'handleDeviceAck',
    'listMobileOperators',
    'pollDevice',
    'provisionDevice',
    'registerDevice',
    'removeAllDevicesFromDeviceGroup',
    'removeDevicesFromDeviceGroup',
    'searchDevice',
    'searchDeviceGroup',
    'searchDeviceMessage',
    'searchDeviceType',
    'searchHomeGPRSIP',
    'searchHomeMobileNumber',
    'searchMasterFeature',
    'sendConfigurationToDevice',
    'sendMessage',
    'setDeviceType',
    'stopTrackingDevice',
    'updateDevice',
    'updateDeviceConfiguration',
    'updateDeviceFeature',
    'updateDeviceGroup',
    'updateDeviceType',
    'updateDeviceTypeConfiguration',
    'updateHomeGPRSIP',
    'updateHomeMobileNumber',
    'updateMasterFeature',
    'upgradeCode',
]

permission_dict = {
    'base': base_list,
    'user': user_list,
    'asset': asset_list,
    'track': tracking_list,
    'device': device_list,
    'geofence': geofencing_list,
    'route': landmarks_routes_list,
}
