#!/usr/bin/env python

from __future__ import print_function
import re
import sys


def replace(match):
    key, version = match.groups()
    inc_version = int(version) + 1
    print("Version now at", inc_version)
    return key + str(inc_version)


def increment_build():
    new_app = ''
    with open('app.yaml', 'r') as app:
        reg = r'(?P<key>\s+MINOR_VERSION:\s+)(?P<version>\d+)'
        new_app = re.sub(reg, replace, app.read())
    with open('app.yaml', 'w') as app:
        app.write(new_app)


def main():
    print("incrementing build")
    increment_build()
    return 0

if __name__ == '__main__':
    sys.exit(main())
